version: "3.7"

configs:
    nginx:
        file: ./nginx/default.conf

secrets:
    digitalocean_creds:
        file: ./nginx/digitalocean.ini.secret
    mysql_root_password:
        file: ./mysql/root_password.secret
    mysql_password:
        file: ./mysql/password.secret

volumes:
    db:
    mail:
    nginx_config:
    website:

networks:
    external:
    internal:
        internal: true

services:
    # https://github.com/docker-library/wordpress/issues/30#issuecomment-145320414
    # The wordpress image doesn't support mail. hectane + the hectane WP plugin
    # / an SMTP plugin fixes the problem. You may need to set up SPF.
    mail:
        image: hectane/hectane:0.3.1
        environment:
            LOGFILE: /dev/stderr
            DEBUG: 1
            # Can't deliver to gmail with this enabled: https://github.com/hectane/hectane/issues/40
            DISABLE_SSL_VERIFICATION: 1
        volumes:
            - mail:/data
        networks:
            - external

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wp-user
            MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
        secrets:
            - mysql_root_password
            - mysql_password
        volumes:
            - db:/var/lib/mysql
        networks:
            - internal

    nginx:
        image: linuxserver/letsencrypt:0.38.0-ls59
        ports:
            - "80:80"
            - "443:443"
        environment:
            TZ: US/Denver
            URL: jeffrey.falgout.name
            SUBDOMAINS: wildcard
            VALIDATION: dns
            DNSPLUGIN: digitalocean
            EMAIL: jeffrey@falgout.email
        configs:
            - source: nginx
              target: /config/nginx/site-confs/default
        secrets:
            - source: digitalocean_creds
              target: /config/dns-conf/digitalocean.ini
        volumes:
            - nginx_config:/config
        networks:
            - external

    wordpress:
        image: wordpress:php7.1-apache
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wp-user
            WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
        secrets:
            - mysql_password
        volumes:
            - website:/var/www/html
        networks:
            - internal
            - external
