#!/usr/bin/env bash
# Ignores local changes to .secret files.

IFS=$'\n'
secrets=( $(find -name *.secret) )
unset IFS

echo "Ignoring ${secrets[*]}"
git update-index --assume-unchanged "${secrets[@]}"
